spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  devtools:
    restart:
      trigger-file: trigger.txt
  #整合jms测试，安装在别的机器，防火墙和端口号记得开放
#  activemq:
#    broker-url: tcp://127.0.0.1:61616
#    user: admin
#    password: admin
#    pool:
#      enabled: true
#      max-connections: 100

activemqUrl: tcp://127.0.0.1:61616
activemqUser: admin
activemqPassword: admin
queueName: common.queue
topicName: common.topic






user.filePath: C:/Users/Ricky/Desktop/image/

#数据库配置#
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      stat-view-servlet:
        login-username: admin
        login-password: admin

  redis:
      database: 0          # Redis数据库索引（默认为0）
      host: 192.168.0.20  # Redis服务器地址
      port: 6379           # Redis服务器连接端口
      password: redis    # Redis服务器连接密码（默认为空）
      pool:
        jedis:
          max-active: 100    # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 10       # 连接池中的最大空闲连接
          max-wait: 100000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      timeout: 5000


#增加打印sql语句，一般用于本地开发测试
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    call-setters-on-nulls: true #Map对象能返值为null的字段
  #开启二级缓存机制
  mapper-locations: classpath:mapper/*Mapper.xml


#定义SpringBoot输出的日志级别
logging:
  level:
    root: info


