server:
  port: 9100

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RickyChan1186/config_cloud.git
          username: 13726261186@163.com
          password: Lovely520
          timeout: 5
          default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/



